name: Build & Push Web to Master

on:
  push:
    branches:
      - master

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Copy Web Build to Temp Folder
        run: |
          mkdir temp_web
          cp -r build/web/* temp_web/

      - name: Checkout Master Again (to commit)
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace build/web with New Build
        run: |
          rm -rf build/web
          mkdir -p build/web
          cp -r temp_web/* build/web/

      - name: Commit Build Folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add build/web
          git commit -m "chore: update web build on push to master" || echo "No changes to commit"
          git push
